chore: remove cargo-spellcheck from nix.flake
Something has changed upstream that's causing issues building
the package on darwin. I haven't found a fix yet, so I'm removing
the package for now. For future reference, the error was:

```
       >   = note: ld: framework not found SystemConfiguration
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >
       >
       > error: could not compile `cargo-spellcheck` (build script) due to previous error
```